name: chat_app_dart
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  build_runner: ^2.4.6
  cloud_firestore: ^5.0.0
  dart_jsonwebtoken: ^2.12.1
  firebase_core: ^3.0.0
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  path_provider: ^2.1.3
  sqflite: ^2.3.3+1
  sqlite3_flutter_libs: ^0.5.23

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
