// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF11rKAHmpW1QjmFPKuQR4zKow1jKq50s',
    appId: '1:56083213883:web:7e95083836fd2cefe3f61e',
    messagingSenderId: '56083213883',
    projectId: 'flutter-chat-app-17b69',
    authDomain: 'flutter-chat-app-17b69.firebaseapp.com',
    storageBucket: 'flutter-chat-app-17b69.appspot.com',
    measurementId: 'G-GD9EDFRXNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt1fZRQqgLycCQrd4GtXXZPf25K2Q-D1M',
    appId: '1:56083213883:android:d36f227a63ee09ffe3f61e',
    messagingSenderId: '56083213883',
    projectId: 'flutter-chat-app-17b69',
    storageBucket: 'flutter-chat-app-17b69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi0BaEKKW8D42NHG3OsPcac2fFqm7Jd9U',
    appId: '1:56083213883:ios:0239a35adca7854fe3f61e',
    messagingSenderId: '56083213883',
    projectId: 'flutter-chat-app-17b69',
    storageBucket: 'flutter-chat-app-17b69.appspot.com',
    iosBundleId: 'com.example.chatAppDart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi0BaEKKW8D42NHG3OsPcac2fFqm7Jd9U',
    appId: '1:56083213883:ios:0239a35adca7854fe3f61e',
    messagingSenderId: '56083213883',
    projectId: 'flutter-chat-app-17b69',
    storageBucket: 'flutter-chat-app-17b69.appspot.com',
    iosBundleId: 'com.example.chatAppDart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF11rKAHmpW1QjmFPKuQR4zKow1jKq50s',
    appId: '1:56083213883:web:4f1f8f0fa338c5e6e3f61e',
    messagingSenderId: '56083213883',
    projectId: 'flutter-chat-app-17b69',
    authDomain: 'flutter-chat-app-17b69.firebaseapp.com',
    storageBucket: 'flutter-chat-app-17b69.appspot.com',
    measurementId: 'G-ZHVV1K3XYE',
  );
}
